-- Disable foreign key constraints temporarily
ALTER TABLE Towary NOCHECK CONSTRAINT ALL;
ALTER TABLE Transporty NOCHECK CONSTRAINT ALL;
ALTER TABLE Miejsca_paletowe NOCHECK CONSTRAINT ALL;
ALTER TABLE Magazynierzy NOCHECK CONSTRAINT ALL;
ALTER TABLE Sektory NOCHECK CONSTRAINT ALL;
ALTER TABLE Kierowcy NOCHECK CONSTRAINT ALL;
ALTER TABLE Klienci NOCHECK CONSTRAINT ALL;

-- Delete data from child tables first
DELETE FROM Towary;
DELETE FROM Transporty;
DELETE FROM Miejsca_paletowe;
DELETE FROM Magazynierzy;
DELETE FROM Sektory;
DELETE FROM Kierowcy;
DELETE FROM Klienci;

-- Re-enable foreign key constraints
ALTER TABLE Towary WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Transporty WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Miejsca_paletowe WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Magazynierzy WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Sektory WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Kierowcy WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Klienci WITH CHECK CHECK CONSTRAINT ALL;
